# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_be_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propsales',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name=12)),
                ('meansp', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('minsp', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('maxsp', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('mediansp', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('totsp', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('nums', models.DecimalField(decimal_places=0, max_digits=3, null=True)),
                ('mhi', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pir', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
