# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_be_app', '0003_auto_20171210_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singfamhouse',
            name='num_sfoo',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True),
        ),
    ]
